name: py35_env
channels:
  - defaults
dependencies:
  - python=3.5
  - opencv=3.3.1
  - matplotlib
  - numpy
  - scipy
  - pyyaml
  - colorama
  - progressbar2
  - pyqt
  - spyder-kernels
  - boost
  - cmake
  - pip
  - conda-build
  - packaging
